name: gpt

on:
  workflow_dispatch:  # 手动触发
    # 使用cron表达式来设置定时任务，这个例子是在每天的中午12点运行
        

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout 仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # 这里可以指定 Python 版本，比如 3.9

    # 安装项目的依赖项（如果有）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有 requirements.txt 文件，取消下一行注释
         pip install -r requirements.txt

    # 运行你的 fofa.py 文件
    - name: Run Python script
      run: |
        python3 fofa.py -k ' "gpt-4o" && icon_hash="1871189255" ' --outputname gpt --endcount 25
    # 运行 list.py 文件
    - name: Run list.py
      run: |
        python3 listquchong.py gpt.txt
    #运行   
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global ziluepan 'github-actions[bot]'
        git config --global ziluepan@foxmail.com 'github-actions[bot]@users.noreply.github.com'
        git add gpt.txt
        git commit -m 'Add gpt.txt'
        git push
